<div class = "ui container" style = "margin-top: 15px;">
	<div class="ui icon positive message">
		<i class="checkmark icon"></i>
		<div class="content">
			<div class="header">
				Successfully Registered
			</div>
			<p>Thank you for your registration. </p>
			<p>You can you go ahead and login</p>
			<p><a href = "<?= @$this->url->get('auth/home/signin'); ?>" class = "ui button">Login Here</a></p>
		</div>
	</div>
</div>