<div class="whole_page">
	<div class = "centered_div">
		<div class = "ui grid banner">
			<div class = "four wide column"><img class="ui medium banner" src="<?= $this->url->get('img/arsenal_logo.png'); ?>"></div>
			<div class = "twelve wide column title-holder">
				<h1 class = "ui header banner_head">Create Account</h1>
			</div>
		</div>
		<div class = "clearfix"></div>
		<form class = "ui form" method="POST" action = "<?= @$this->url->get('auth/home/signup'); ?>">
			<div class = "field">
				<label>First Name</label>
				<input type = "text" name = "first_name"/>
			</div>

			<div class = "field">
				<label>Last Name</label>
				<input type = "text" name = "last_name"/>
			</div>

			<div class = "field">
				<label>Email Address</label>
				<input type = "text" name = "email_address"/>
			</div>

			<div class = "field">
				<label>Username</label>
				<input type = "text" name = "username"  />
			</div>

			<div class = "field">
				<label>Password</label>
				<input type = "password" name = "password"  />
			</div>

			<div class = "field">
				<label>Confirm Password</label>
				<input type = "password" name = "confirm_password"  />
			</div>

			<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>

			<button class="negative fluid ui button">Create Account</button>
		</form>
	</div>
</div>