<div class="whole_page">
	<div class = "centered_div">
		<img class="ui medium circular image logo" src="<?= $this->url->get('img/arsenal_logo.png'); ?>">
		<p><?php echo $this->flash->output() ?></p>
		<form class = "ui form" method="POST" action = "<?= @$this->url->get('auth/home/signin'); ?>">
			<div class = "field">
				<label>Username</label>
				<input type = "text" name = "username"  />
			</div>
			<div class = "field">
				<label>Password</label>
				<input type = "password" name = "password"  />
			</div>

			<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>" value="<?php echo $this->security->getToken() ?>"/>

			<button class="negative fluid ui button">Submit</button>

		</form>
	</div>
</div>