<script type="text/javascript">
	$('.ui.form')
		.form({
			fields:{
				first_name		: {
					identifier	: "first_name",
					rules	: [{
						type	: 'empty',
						prompt	: 'Please enter your First Name'
					}]
				},
				last_name		: {
					identifier	: "last_name",
					rules		: [{
						type	: 'empty',
						prompt	: 'Please enter your Last Name'
					}]
				},
				email_address	: {
					identifier	: "email_address",
					rules		: [{
						type	: 'empty',
						prompt	: 'Please enter your email address'
					},
					{
						type	: 'email',
						prompt	: 'Please enter a valid email address'
					}]
				},
				username		: {
					identifier	: "username",
					rules		: [{
						type	: 'empty',
						prompt	: 'Please enter a username'
					},{
						type	: 'minLength[5]',
						prompt	: 'Your username has to be at least 5 characters long'
					}]
				},
				password		: {
					identifier	: "password",
					rules		: [{
						type	: 'empty',
						prompt	: 'Please enter a password'
					}]
				},
				confirm_password: {
					identifier	: "confirm_password",
					rules		: [{
						type	: 'empty',
						match	: 'You must confirm your password'
					},{
						type	: 'match[password]',
						prompt	: 'Your passwords must match'
					}]
				}
			}
			
		});
</script>