<div class = "ui thin left vertical labeled icon menu inverted sidebar">
	<a href="<?php echo $this->url->get('dashboard'); ?>" class = "item">
		<i class = "home icon"></i>
		Home
	</a>
	<a href="<?php echo $this->url->get('dashboard/player/'); ?>" class = "item">
		<i class = "user icon"></i>
		Players
	</a>
	<a href="<?php echo $this->url->get('dashboard'); ?>" class = "item">
		<i class = "table icon"></i>
		League Table
	</a>
	<a href="#" class = "item">
		<i class = "sort numeric ascending icon"></i>
		Results
	</a>
	<a href="#" class = "item">
		<i class = "soccer icon"></i>
		Fixtures
	</a>
	<a href="#" class = "item">
		<i class = "users icon"></i>
		Teams
	</a>
	<a href="#" class = "item">
		<i class = "trophy icon"></i>
		Competitions
	</a>
	<a href="#" class = "item">
		<i class = "sign out icon"></i>
		Sign Out
	</a>
</div>
<div class = "ui top fixed stackable main menu">
	<div class = "item" id = "reveal" style="cursor: pointer; ">
		<img src="<?php echo $this->url->get('img/arsenal_logo.png'); ?>">
	</div>
</div>
<div class = "pusher">
	<div class = "full height">
		<div class = "custom-container">
			<?= @$content; ?>
		</div>	
	</div>
</div>